// FIXME: Change this image ASAP. I hate this gay ass image
import heroImage from "../assets/SAM.jpeg";

const Hero = () => {
  return (
    <section className="py-20 flex flex-col md:flex-row items-center justify-between gap-10">
      <div className="flex-1">
        <h1 className="text-7xl font-black lexend-mega-hero text-black leading-none mb-2">
          Hello. <br /> I'm Sammie!
        </h1>
        <p className="text-2xl lexend-mega-sub font-medium max-w-md border-l-4 font-mono text-black border-black pl-4">
          B. Tech Student and Developer, currently dabbling in low level
          systems.
        </p>
      </div>

      <div className="w-64 h-64 border-2 border-black bg-white shadow-hard-lg flex items-center justify-center p-4">
        <div className="w-full h-full border-2 border-black flex flex-col">
          <div className="flex-1 flex items-center justify-center border-b-2 border-r-1 border-black">
            {/*TODO: Add a better image, one generated by my Dot Matrix image converter*/}
            <span className="text-6xl text-black">
              <img src={heroImage} className="contrast-125 brightness-100 border-2 border-black"/>
            </span>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;
