// FIXME: Change this image ASAP. I hate this ass image
import heroImage from "../assets/SAM.jpeg";

const Hero = () => {
  return (
    <section className="py-20 flex flex-col md:flex-row items-center justify-between gap-10">
      <div className="flex-1">
        {/* TODO: Make this bolder and better*/}
        <h1 className="text-7xl font-black sora text-black leading-none mb-4">
          Hello. <br /> I'm Sammie!
        </h1>
        <p className="text-2xl sora-sub font-medium max-w-md border-l-4 font-mono text-black border-black pl-4">
          B. Tech Student and Developer, currently dabbling in low level
          systems.
        </p>
      </div>

      <div class="w-64 bg-white border-4 border-black hover:translate-x-1 hover:shadow-[8px_8px_0px_rgba(0,0,0,1)] grid place-content-center">
        <div>
          {/*TODO: Add a better image, one generated by my Dot Matrix image converter*/}
          <span className="text-6xl text-black">
            <img
              src={heroImage}
              className="contrast-125 brightness-100 border-black"
            />
          </span>
        </div>
      </div>
    </section>
  );
};

export default Hero;
